#!/usr/bin/env python3
"""Refreshes currency_rates.json - daily FX rates used to normalise salaries
to USD for cross-source/cross-currency comparison (collectors/_common.py's
normalise_salary()).

Source: Frankfurter (https://api.frankfurter.dev) - free, no API key, no
signup, tracks ECB daily reference rates for ~30 major currencies. Chosen
over paid/rate-limited alternatives (ExchangeRate-API, Open Exchange Rates)
specifically because it requires zero credentials and has no documented
rate limit for normal use - a good fit for a scheduled GitHub Actions job
that runs once a day.

Limitation worth knowing: Frankfurter covers ECB-tracked currencies, which
is the ~30 major world currencies - this includes KES, but does not cover
every African currency (e.g. some smaller ones may be missing). Currencies
we don't get a rate for simply won't normalise - normalise_salary() already
handles a missing currency by returning (None, None) rather than guessing.

Usage:
    python3 refresh_fx.py --out ../currency_rates.json
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def fetch_rates() -> dict[str, float]:
    """Returns {currency_code: units_of_that_currency_per_1_USD}.

    Frankfurter's response for base=USD gives e.g. {"KES": 129.4, "EUR": 0.86}
    meaning 1 USD = 129.4 KES. normalise_salary() in _common.py wants the
    inverse - "1 unit of KES in USD" - so we invert every rate here, once,
    rather than making every caller do that division.
    """
    import requests

    resp = requests.get("https://api.frankfurter.dev/v1/latest", params={"base": "USD"}, timeout=30)
    resp.raise_for_status()
    payload = resp.json()

    raw_rates = payload.get("rates", {})
    if not raw_rates:
        raise RuntimeError(f"Frankfurter returned no rates: {payload}")

    # Invert: units-per-USD -> USD-per-unit. USD itself is always 1:1.
    usd_per_unit = {"USD": 1.0}
    for code, units_per_usd in raw_rates.items():
        if units_per_usd and units_per_usd > 0:
            usd_per_unit[code] = round(1.0 / units_per_usd, 8)

    return usd_per_unit


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="currency_rates.json")
    args = parser.parse_args()

    try:
        rates = fetch_rates()
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: failed to fetch FX rates: {exc}", file=sys.stderr)
        # Don't overwrite a previously-good rates file with a failure -
        # same "refuse to blank good data" principle as refresh_feed.py.
        sys.exit(1)

    output = {
        "_comment": "USD value of 1 unit of each currency. Source: Frankfurter (ECB daily reference rates). Regenerated by scripts/refresh_fx.py.",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "source": "https://api.frankfurter.dev",
        "rates_to_usd": rates,
    }

    out_path = Path(args.out)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)
        f.write("\n")
    print(f"Wrote {len(rates)} currency rates to {out_path}")


if __name__ == "__main__":
    main()
