"""Registry loading and compatibility helpers for the Kazi Sasa feed.

Phase 1 makes ``config/organisations.json`` and
``config/source_registry.json`` authoritative. The older per-ATS board files
and root ``sources.json`` remain available for external tooling, but are
reproducible generated artifacts.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ADAPTER_FIELD = {
    "greenhouse": "board_token",
    "lever": "site",
    "ashby": "board_slug",
    "pinpoint": "subdomain",
    "recruitee": "subdomain",
    "cornerstone": "career_site_url",
    "successfactors": "career_site_url",
    "oracle_cx": "career_site_url",
    "official_html": "listing_url",
    "pageup": "career_site_url",
    "government_html": "listing_url",
    "government_pdf": "listing_url",
    "government_circular": "listing_url",
    "government_json": "listing_url",
    "workday": "career_site_url",
    "smartrecruiters": "company_identifier",
    "workable": "account_slug",
    "multinational_html": "listing_url",
    "public_institution_html": "listing_url",
}
LEGACY_CONFIG_FILE = {
    "greenhouse": "greenhouse_boards.json",
    "lever": "lever_boards.json",
    "ashby": "ashby_boards.json",
    "pinpoint": "pinpoint_boards.json",
    "recruitee": "recruitee_boards.json",
}


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def load_organisation_registry(path: Path) -> dict[str, Any]:
    data = load_json(path)
    if not isinstance(data.get("organisations"), list):
        raise ValueError(f"{path} must contain an organisations list")
    return data


def load_source_registry(path: Path) -> dict[str, Any]:
    data = load_json(path)
    if not isinstance(data.get("sources"), list):
        raise ValueError(f"{path} must contain a sources list")
    return data


def adapter_boards(registry: dict[str, Any], adapter: str, *, enabled_only: bool = True) -> list[dict[str, Any]]:
    """Return legacy collector board rows from the organisation registry.

    Ordering is deterministic: organisation order first, then the source order
    within each organisation. That preserves the collector order used before
    Phase 1 and therefore avoids accidental changes to cross-source precedence.
    """
    if adapter not in ADAPTER_FIELD:
        raise ValueError(f"unsupported adapter {adapter!r}")

    identifier_field = ADAPTER_FIELD[adapter]
    boards: list[dict[str, Any]] = []
    for organisation in registry.get("organisations", []):
        if enabled_only and not organisation.get("enabled", True):
            continue
        for source in organisation.get("sources", []):
            if source.get("adapter") != adapter:
                continue
            if enabled_only and not source.get("enabled", True):
                continue
            row = {
                "name": source.get("legacy_name") or organisation["name"],
                identifier_field: source["identifier"],
                "type": source.get("legacy_type") or organisation.get("organisation_type", "private"),
            }
            if source.get("notes"):
                row["notes"] = source["notes"]
            if adapter not in LEGACY_CONFIG_FILE:
                row["organisation_id"] = organisation["id"]
                row["organisation_type"] = organisation.get("organisation_type")
                row["countries"] = organisation.get("countries", [])
                row["languages"] = organisation.get("languages", [])
                row.update(source.get("config") or {})
            boards.append(row)
    return boards


def legacy_ats_payload(registry: dict[str, Any], adapter: str) -> dict[str, Any]:
    return {
        "_comment": (
            f"GENERATED from config/organisations.json for backward compatibility. "
            f"Do not edit this file directly; update the organisation registry and run "
            f"python3 scripts/generate_legacy_configs.py. Adapter: {adapter}."
        ),
        "boards": adapter_boards(registry, adapter),
    }


def legacy_sources_payload(source_registry: dict[str, Any]) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    for source in source_registry.get("sources", []):
        row = {
            "name": source["name"],
            "domain": source.get("domain"),
            "default_confidence": source["default_confidence"],
        }
        if source.get("notes"):
            row["notes"] = source["notes"]
        rows.append(row)
    return {
        "_comment": (
            "GENERATED from config/source_registry.json for backward compatibility. "
            "Do not edit this file directly; update the source registry and run "
            "python3 scripts/generate_legacy_configs.py."
        ),
        "sources": rows,
        "default_for_unknown_source": source_registry.get("default_for_unknown_source", "unverified"),
    }


def organisation_index(registry: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {organisation["id"]: organisation for organisation in registry.get("organisations", [])}


def source_lookup(source_registry: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {source["id"]: source for source in source_registry.get("sources", [])}
